### ISSUE TITLE
AttributeError: 'datetime.date' object has no attribute 'date'

### ISSUE THREAD

**Issue by sisihagen** [partizand/gnucashreport#1]
Hi,

i try today to run your code but it ends with:

```
gcreport ~/.finance/siefkesilvio.gnucash ~/Downloads/reort.xlsx
Opening file /home/siefke/.finance/siefkesilvio.gnucash ...
Traceback (most recent call last):
  File "/home/siefke/.python/bin/gcreport", line 11, in <module>
    sys.exit(main())
  File "/home/siefke/.python/lib/python3.6/site-packages/gnucashreport/gcreportcli.py", line 30, in main
    gcrep.open_book_file(p_args.gnucash_file, open_if_lock=p_args.open_if_lock)
  File "/home/siefke/.python/lib/python3.6/site-packages/gnucashreport/gnucashdata.py", line 120, in open_book_file
    self.open_book_sql(sqlite_file=filename, readonly=readonly, open_if_lock=open_if_lock)
  File "/home/siefke/.python/lib/python3.6/site-packages/gnucashreport/gnucashdata.py", line 171, in open_book_sql
    self._after_read()
  File "/home/siefke/.python/lib/python3.6/site-packages/gnucashreport/gnucashdata.py", line 392, in _after_read
    lambda x: pandas.to_datetime(x.date()))
  File "/home/siefke/.python/lib/python3.6/site-packages/pandas/core/series.py", line 3192, in apply
    mapped = lib.map_infer(values, f, convert=convert_dtype)
  File "pandas/_libs/src/inference.pyx", line 1472, in pandas._libs.lib.map_infer
  File "/home/siefke/.python/lib/python3.6/site-packages/gnucashreport/gnucashdata.py", line 392, in <lambda>
    lambda x: pandas.to_datetime(x.date()))
AttributeError: 'datetime.date' object has no attribute 'date'

```

python --version
Python 3.6.5

Silvio

**Comment by partizand** [comment]
Hi
I saw. While looking for a reason and remember the code.
Wait a few days.

I tested only on windows, maybe this is the reason. I use it myself, it works.

**Comment by partizand** [comment]
Fixed, use 0.2.3 version (works with GnuCash 3.1).
There's nobody to test. For me works

**Comment by sisihagen** [comment]
Works :) perfect thank you. 

Silvio
